name: "Vprofile IAC"
on: 
    push:
        branches:
            - main
            - stage
        paths:
            - terraform/**
    pull_request: 
        branches:
            - main
        paths:
            - terraform/**

env:
    # Credentials for deployment to AWS
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_}}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    # S3 Bucket for the terraform state
    BUCKET_IF_STATE: ${{ secrets.BUCKET_IF_STATE }}
    AWS_REGION: ap-south-1
    EKS_CLUSTER: vprofile-eks

jobs:
    terraform:
        name: "Apply terraform code changes"
        runs_on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ./terraform
        
        steps:
            - name: Check source code
                uses: actions/checkout@v4
            
            - name: Setup Terraform with specified version on runner 
                uses: hashicorp/setup-terraform@v3
            #    with: 
            #     terraform_version: "1.1.7"
            - name: Terraform init
                id: init
                run: terraform init -backend-config="bucket=$BUCKET_IF_STATE"

            - name: Terraform format
                id: fmt
                run: terraform fmt -check

            - name: Terraform validate
                id: validate
                run: terraform validate

            - name: Terraform plan
                id: plan
                run: terraform plan -no-color -input=false -out planfile
                continue-on-error: true
            
            - name: Terraform plan status
                if: stops.plan.outcome == 'failure'
                run: exit 1 
            